### ISSUE TITLE
ESP32 support

### ISSUE THREAD

**Issue by basementmedia2** [bxparks/AceTime#64]
Hi Brian,

just wanted to use your great library with an ESP32 Board and got a bunch of error messages after sketch upload.

If i just include the library by

`#include <AceTime.h>`

i get a huge fault message starting like this (just a few lines, complete message is very long):
```
In file included from /home/basementmedia/.arduino15/packages/esp32/hardware/esp32/1.0.6/cores/esp32/WString.h:29:0,
                 from /home/basementmedia/.arduino15/packages/esp32/hardware/esp32/1.0.6/cores/esp32/Arduino.h:146,
                 from sketch/waterbot_v44_esp32_v2.ino.cpp:1:
/home/basementmedia/Arduino/libraries/AceTime/src/ace_time/common/DateStrings.h: In static member function 'static const char* ace_time::DateStrings::getStringAt(const char* const*, uint8_t)':
/home/basementmedia/.arduino15/packages/esp32/hardware/esp32/1.0.6/cores/esp32/pgmspace.h:52:14: error: 'typeof_' was not declared in this scope
   typeof(addr) _addr = (addr); \
              ^
/home/basementmedia/Arduino/libraries/AceTime/src/ace_time/common/DateStrings.h:73:28: note: in expansion of macro 'pgm_read_ptr'
       return (const char*) pgm_read_ptr(&strings[i]);
                            ^
/home/basementmedia/.arduino15/packages/esp32/hardware/esp32/1.0.6/cores/esp32/pgmspace.h:53:21: error: '_addr' was not declared in this scope
   *(void * const *)(_addr); \
                     ^
/home/basementmedia/Arduino/libraries/AceTime/src/ace_time/common/DateStrings.h:73:28: note: in expansion of macro 'pgm_read_ptr'
       return (const char*) pgm_read_ptr(&strings[i]);
                            ^
/home/basementmedia/.arduino15/packages/esp32/hardware/esp32/1.0.6/cores/esp32/pgmspace.h:53:27: error: void value not ignored as it ought to be
   *(void * const *)(_addr); \
                           ^
```

Is this library not compatible to the ESP32?

Best wishes 

Daniel

**Comment by bxparks** [comment]
I'm not able to reproduce this error. Works fine on my ESP32, using v1.0.6.

Send me more info about your environment:
* the ESP32 board that you are using
* the Arduino IDE compiler settings (board type, etc)
* copy of the sketch that you are compiling, stripped down to its minimal reproducible form, in other words, take out everything that is not needed to reproduce the bug

**Comment by bxparks** [comment]
Closing after no response. Please reopen if you have more info.
